export const FEATURED_SPECIES = [
  {
    id: 'saltwater-crocodile',
    commonName: 'Saltwater Crocodile',
    scientificName: 'Crocodylus porosus',
    description: 'The largest living reptile, found across Southeast Asia and northern Australia.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Crocodylus_porosus_2.jpg/800px-Crocodylus_porosus_2.jpg',
    continent: 'Asia / Australia',
    conservation: 'Least Concern',
    overview: 'The saltwater crocodile is the largest living reptile and crocodilian known to science. Males can reach lengths of up to 6–7 meters and weigh over 1,000 kg. They are apex predators and can be found in saltwater habitats and brackish wetlands from India to Australia.',
    habitat: 'Saltwater crocodiles inhabit brackish and freshwater regions including estuaries, deltas, lagoons, and lower stretches of rivers. They are strong swimmers and have been spotted far out at sea.',
    behavior: 'Highly territorial and aggressive, saltwater crocodiles are ambush predators. They are capable of explosive bursts of speed both in water and on land. They regulate body temperature through basking in sunlight.',
    diet: 'Saltwater crocodiles are opportunistic feeders. Juveniles eat insects, amphibians, and small fish. Adults prey on fish, turtles, birds, buffalo, and even sharks. They use the "death roll" technique to subdue large prey.',
    conservationDetails: 'Once hunted nearly to extinction for their hides, saltwater crocodiles have recovered significantly due to legal protection and farming programs. They are currently listed as Least Concern by the IUCN.',
    length: '4–6 m (avg male)',
    weight: '400–1,000 kg',
    lifespan: '70+ years',
    kingdom: 'Animalia',
    classType: 'Reptilia',
    order: 'Crocodilia',
    family: 'Crocodylidae',
    regions: ['India', 'Southeast Asia', 'Papua New Guinea', 'Northern Australia'],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Crocodylus_porosus_2.jpg/800px-Crocodylus_porosus_2.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Saltwater_crocodile_head.jpg/800px-Saltwater_crocodile_head.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Crocodylus_porosus_zoo.jpg/800px-Crocodylus_porosus_zoo.jpg',
    ],
    quickFacts: [
      { icon: '🦷', value: '66', label: 'Teeth' },
      { icon: '📏', value: '6.17m', label: 'Max Length' },
      { icon: '⚖️', value: '1,000kg', label: 'Max Weight' },
      { icon: '🌊', value: '29 km/h', label: 'Swimming Speed' },
    ],
  },
  {
    id: 'nile-crocodile',
    commonName: 'Nile Crocodile',
    scientificName: 'Crocodylus niloticus',
    description: "Africa's largest freshwater predator and one of the most dangerous animals on Earth.",
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Nile_crocodile_head.jpg/800px-Nile_crocodile_head.jpg',
    continent: 'Africa',
    conservation: 'Least Concern',
    overview: 'The Nile crocodile is Africa\'s largest freshwater predator. It is the second largest reptile in the world and is responsible for hundreds of human fatalities each year. They inhabit rivers, lakes, and marshlands across sub-Saharan Africa.',
    habitat: 'Nile crocodiles prefer large rivers, lakes, and reservoirs but also inhabit swamps and marshes. They are territorial and patrol stretches of river bank.',
    behavior: 'Social animals that tolerate each other at feeding sites, Nile crocodiles have complex hierarchy systems. Females are devoted mothers, guarding nests and carrying hatchlings to water.',
    diet: 'Fish form the bulk of their diet, but Nile crocodiles will attack almost any animal that comes to the water\'s edge including zebras, wildebeest, and hippos.',
    conservationDetails: 'Despite historical overhunting, Nile crocodile populations have stabilized. They remain vulnerable in some parts of West Africa but are stable overall.',
    length: '3.5–5 m (avg male)',
    weight: '225–750 kg',
    lifespan: '45 years',
    kingdom: 'Animalia',
    classType: 'Reptilia',
    order: 'Crocodilia',
    family: 'Crocodylidae',
    regions: ['Sub-Saharan Africa', 'Madagascar', 'Nile Basin'],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Nile_crocodile_head.jpg/800px-Nile_crocodile_head.jpg',
    ],
    quickFacts: [
      { icon: '📏', value: '5m', label: 'Avg Length' },
      { icon: '⚖️', value: '750kg', label: 'Max Weight' },
      { icon: '🥚', value: '60', label: 'Eggs per Clutch' },
      { icon: '⏱️', value: '45 yrs', label: 'Lifespan' },
    ],
  },
  {
    id: 'american-alligator',
    commonName: 'American Alligator',
    scientificName: 'Alligator mississippiensis',
    description: 'A conservation success story — recovered from near-extinction in the United States.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/American_Alligator.jpg/800px-American_Alligator.jpg',
    continent: 'North America',
    conservation: 'Least Concern',
    overview: 'The American alligator is one of the greatest conservation success stories. Once endangered due to hunting and habitat loss, strict legal protections allowed populations to fully recover. They are found primarily in the southeastern United States.',
    habitat: 'American alligators live in freshwater environments including swamps, marshes, rivers, lakes, and ponds. They dig burrows called "gator holes" which provide refuge during dry and cold periods.',
    behavior: 'Generally less aggressive than crocodiles, they are still dangerous. Males bellow during mating season to attract females. They are known to use tools — balancing sticks on their snouts to lure birds during nesting season.',
    diet: 'Alligators eat fish, invertebrates, frogs, birds, and mammals. Juveniles eat insects and small animals. Large adults can take deer, wild boar, and even smaller alligators.',
    conservationDetails: 'Removed from the endangered species list in 1987 following population recovery. Now legally harvested under controlled programs in several states.',
    length: '2.6–4.6 m (avg male)',
    weight: '180–450 kg',
    lifespan: '35–50 years',
    kingdom: 'Animalia',
    classType: 'Reptilia',
    order: 'Crocodilia',
    family: 'Alligatoridae',
    regions: ['Florida', 'Louisiana', 'Georgia', 'South Carolina', 'Texas'],
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/American_Alligator.jpg/800px-American_Alligator.jpg',
    ],
    quickFacts: [
      { icon: '📏', value: '4.6m', label: 'Max Length' },
      { icon: '⚖️', value: '450kg', label: 'Max Weight' },
      { icon: '🦷', value: '80', label: 'Teeth' },
      { icon: '🌡️', value: '32°C', label: 'Basking Temp' },
    ],
  },
]